services:
  database:
    image: postgres:13
    container_name: database
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app_network

  api:
    container_name: api
    env_file: .env
    build: .
    volumes:
      - ./app:/app
    ports:
      - '8080:8080'
    depends_on:
      - database
    networks:
      - app_network

volumes:
  postgres:

networks:
  app_network:
    driver: bridge