"""Create m_user and m_favorites tables

Revision ID: 36b34982d323
Revises: ceb45bb35440
Create Date: 2024-09-08 20:02:23.297597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b34982d323'
down_revision: Union[str, None] = 'ceb45bb35440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_favorites', 'activity_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_favorites', sa.Column('activity_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
